import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {businessPeriod,classify,makeSnapshot,auditWages} from './prime-cost-model.mjs';
const line={location:'Montrose - Betelgeuse Betelgeuse',vendor:'External supplier',invoice_date:'2026-09-17',invoice_number:'1',status:'Completed',doc_type:'Invoice',category:'Protein',description:'Chicken',line_total:100};
function fixture(){return {from:'2026-09-17',through:'2026-09-17',invoices:[line],status:{last_ingest:'2026-09-18T10:00:00Z',invoice_date_range:{to:'2026-09-17'}},rates:[{restaurant_id:3,biweekly_cents:14000,excludes_owner_comp:true},{restaurant_id:4,biweekly_cents:28000,excludes_owner_comp:true}],records:['Montrose','Washington'].flatMap(restaurantGuid=>['sales','labor'].map(type=>({restaurantGuid,businessDate:20260917,type,data:{businessDate:20260917,netSales:1000,totalWages:100}})))}}
test('complete two-store amounts and calendar-day salary calculation',()=>{const r=makeSnapshot(fixture());assert.equal(r.days[0].sales,2000);assert.equal(r.days[0].wages,200);assert.equal(r.days[0].salaries,30);assert.equal(r.groups.food,100)});
test('verified August payroll overrides older service rates and reconciles owner deduction',()=>{const b=JSON.parse(fs.readFileSync(new URL('./prime-salary-baseline.json',import.meta.url)));const f={...fixture(),salaryBaseline:b};const r=makeSnapshot(f);assert.equal(r.salaryBiweekly,5571.66);assert.equal(r.days[0].salaries,5571.66/14);assert.match(r.salaryBasis,/August 17–30/);assert.throws(()=>makeSnapshot({...f,salaryBaseline:{...b,ownerExcludedCents:0}}))});
test('missing and duplicate Toast responses fail closed',()=>{for(const mutate of [r=>r.pop(),r=>r.push(r[0]),r=>r[0].data.businessDate=20260916,r=>r[0].restaurantGuid='Other']){const f=fixture();mutate(f.records);assert.throws(()=>makeSnapshot(f))}});
test('unknown categories, sources and uncompleted invoices require review',()=>{assert.equal(classify({...line,category:'New food taxonomy'}),'review');assert.equal(classify({...line,location:'Other'}),'review');assert.equal(classify({...line,status:'Pending'}),'review')});
test('owner category rules are applied',()=>{for(const category of ['Paper - Food Costs','Dairy'])assert.equal(classify({...line,category}),'food');for(const category of ['Mixer','Bar Produce','Drink Presentation (Garnishes)'])assert.equal(classify({...line,category}),'bar');assert.equal(classify({...line,category:'Kitchen Supply'}),'excluded')});
test('deposit exclusions are narrow and preserve genuine goods credits',()=>{assert.equal(classify({...line,category:'Beer',description:'Blue Owl keg DEPOSIT'}),'bar');assert.equal(classify({...line,category:'Beer',description:'EMPTY-MICROSTAR 1/2 KEG'}),'deposits');assert.equal(classify({...line,category:'Beer',description:'Unknown shell credit'}),'review');const f=fixture();f.invoices=[{...line,line_total:-20}];assert.equal(makeSnapshot(f).groups.food,-20)});
test('seed and internal transfer are not counted as external goods',()=>{assert.equal(classify({...line,category:'inventory_seed'}),'excluded');assert.equal(classify({...line,vendor:'Betelgeuse Betelgeuse'}),'excluded')});
test('incomplete salary configuration fails closed',()=>{const f=fixture();f.rates[0].excludes_owner_comp=false;assert.throws(()=>makeSnapshot(f));const other=fixture();other.rates[1].restaurant_id=3;assert.throws(()=>makeSnapshot(other))});
test('duplicate invoice lines are rejected',()=>{const f=fixture();f.invoices.push(line);assert.throws(()=>makeSnapshot(f))});
test('reconciled identical rows with distinct source identities are counted, repeated identities rejected',()=>{const f=fixture();f.invoices=[{...line,source_line_id:'invoice:0'},{...line,source_line_id:'invoice:1'}];assert.equal(makeSnapshot(f).groups.food,200);f.invoices.push(f.invoices[0]);assert.throws(()=>makeSnapshot(f),/Duplicate invoice/)});
test('undated lines are explicitly flagged instead of assigned upload dates',()=>{const f=fixture();f.invoices=[{...line,invoice_date:null}];const r=makeSnapshot(f);assert.equal(r.undatedLines,1);assert.equal(r.groups.food,0)});
test('Chicago closeout and month boundary preserve completed business dates',()=>{assert.deepEqual(businessPeriod(new Date('2026-10-01T08:59:00Z')),{from:'2026-09-01',through:'2026-09-29'});assert.deepEqual(businessPeriod(new Date('2026-10-01T09:00:00Z')),{from:'2026-09-01',through:'2026-09-30'});assert.deepEqual(businessPeriod(new Date('2026-10-02T09:00:00Z')),{from:'2026-10-01',through:'2026-10-01'})});
test('owner wages excluded while genuine hybrid wages retained and manager overlap flagged',()=>{const staff=[{guid:'c',firstName:'Chris',lastName:'Cusack'},{guid:'g',firstName:'Grace',lastName:'Burke'},{guid:'v',firstName:'Virginia',lastName:'Mikalonis'},{guid:'j',firstName:'Jason',lastName:'Benfield'}];const entries=['c','g','v','j'].map(employeeGuid=>({guid:employeeGuid,employeeGuid,businessDate:20260917,regularHours:2,overtimeHours:0,hourlyWage:5}));const a=auditWages(staff,entries,'2026-09-17','2026-09-17');assert.equal(a.ownerExcluded,20);assert.equal(a.byDay[20260917].total-a.byDay[20260917].owner,20);assert.equal(a.managerOverlap,10);assert.throws(()=>auditWages(staff,[...entries,entries[0]],'2026-09-17','2026-09-17'))});
