import test from 'node:test';import assert from 'node:assert/strict';import {accessToken} from './sandcastles-auth.mjs';import {mapSocial,channels,collectSandcastles} from './sandcastles.mjs';
const now=new Date('2026-09-20T17:00:00Z'),previous={checkedAt:'2026-09-19T17:00:00Z',accounts:Object.keys(channels).map(handle=>({handle,name:handle}))};
function payload(){const metric=value=>Object.fromEntries(Object.values(channels).map(id=>[id,value]));return {charts:{points:Array.from({length:7},(_,i)=>({date:'2026-09-'+(14+i),followers:metric(100),views:metric(200),posts:metric(2)})),views_baseline:metric(150),followers_baseline:metric(90)}};}
test('refresh rotation persists before token use; failed OAuth retains prior credentials',async()=>{let persisted;const auth={client_id:'test',refresh_token:'old',expires_at:0};const token=await accessToken({auth,now,persist:v=>persisted=v,fetchImpl:async()=>({ok:true,json:async()=>({access_token:'new-access',refresh_token:'new-refresh',expires_in:3600,token_type:'Bearer'})})});assert.equal(token,'new-access');assert.equal(persisted.refresh_token,'new-refresh');assert.equal(auth.refresh_token,'old');await assert.rejects(accessToken({auth,now,persist:()=>assert.fail(),fetchImpl:async()=>({ok:false})}));});
test('all three verified handles required, partial or wrong workspace stats rejected',()=>{const result=mapSocial(previous,payload(),now);assert.deepEqual(result.accounts.map(a=>a.handle),Object.keys(channels));assert.equal(result.accounts[0].views,'50');const partial=payload();delete partial.charts.points.at(-1).followers[channels.betelgeusemontrose];assert.throws(()=>mapSocial(previous,partial,now));assert.throws(()=>mapSocial({...previous,accounts:previous.accounts.slice(1)},payload(),now));assert.throws(()=>mapSocial({...previous,accounts:previous.accounts.map(a=>({...a,handle:'wrong'}))},payload(),now));const noBaseline=payload();noBaseline.charts.followers_baseline={};assert.equal(mapSocial(previous,noBaseline,now).accounts[0].gained,null);});
test('within one hour, disabled and overnight collectors make no auth or provider calls',async()=>{const clientFactory=()=>assert.fail(),fetchImpl=()=>assert.fail();for(const options of [{env:{}},{env:{SANDCASTLES_ENABLED:'true'},previous:{...previous,checkedAt:'2026-09-20T16:30:00Z'}},{env:{SANDCASTLES_ENABLED:'true'},now:new Date('2026-09-20T07:00:00Z')}])assert.equal(await collectSandcastles({previous,now,auth:null,clientFactory,fetchImpl,...options}),null);});
test('collector invokes only free personal analytics and failure never mutates prior snapshot',async()=>{const calls=[],copy=JSON.stringify(previous);const client={connect:async()=>{},close:async()=>{},callTool:async request=>{calls.push(request);return {structuredContent:payload()};}};const result=await collectSandcastles({previous,now,env:{SANDCASTLES_ENABLED:'true'},auth:{client_id:'test',access_token:'test-access',expires_at:now.getTime()+3600000},clientFactory:()=>client});assert.deepEqual(calls,[{name:'get_personal_analytics',arguments:{}}]);assert.equal(result.accounts.length,3);assert.equal(JSON.stringify(previous),copy);client.callTool=async()=>({isError:true});await assert.rejects(collectSandcastles({previous,now,env:{SANDCASTLES_ENABLED:'true'},auth:{client_id:'test',access_token:'test-access',expires_at:now.getTime()+3600000},clientFactory:()=>client}));assert.equal(JSON.stringify(previous),copy);});
test('future, invalid calendar and regressed periods cannot replace last-good analytics',()=>{const dated={...previous,periodFrom:'2026-09-14',periodThrough:'2026-09-20'};const move=days=>{const result=payload();for(const point of result.charts.points)point.date=new Date(Date.parse(point.date)+days*86400000).toISOString().slice(0,10);return result;};assert.throws(()=>mapSocial(dated,move(1),now),/Future or regressed/);assert.throws(()=>mapSocial(dated,move(-1),now),/Future or regressed/);const invalid=payload();invalid.charts.points[0].date='2026-02-31';assert.throws(()=>mapSocial(dated,invalid,now),/Invalid analytics dates/);assert.equal(mapSocial(dated,payload(),now).periodThrough,'2026-09-20');});
test('posts are already cumulative within the seven-day chart; do not subtract lifetime baseline or sum chart points',()=>{const data=payload();data.charts.posts_baseline=Object.fromEntries(Object.values(channels).map(id=>[id,178]));const mapped=mapSocial(previous,data,now);assert.equal(mapped.accounts[0].posts,2);assert.equal(mapped.upstreamIntervalHours,1);assert.equal(mapped.sourceRefreshHours,12);});
test('one hourly read is eligible exactly one hour after the previous verified read',async()=>{let calls=0;await collectSandcastles({previous:{...previous,checkedAt:'2026-09-20T16:00:00Z'},now,env:{SANDCASTLES_ENABLED:'true'},auth:{client_id:'test',access_token:'test',expires_at:now.getTime()+3600000},clientFactory:()=>({connect:async()=>{},close:async()=>{},callTool:async()=>{calls++;return {structuredContent:payload()};}})});assert.equal(calls,1);});
